### ISSUE TITLE
Suggestion: Change the zip's base directory.

### ISSUE THREAD

**Issue by gphg** [2dengine/love.maker#3]
Current version is on root of project here `main.lua` located. I suggest it should be possible to make a zip out of a project's sub-directory.

Suggestion example:
```lua
love.maker = require("maker.main")
local assetBuild = love.maker.newBuild("assetDir", "txt", "png", "json", "xml")
assetBuild:save("gameasset.zip") -- iterate over "assetDir" and save into a zip.
```

I managed to get it work without `love.maker` and directly using `zapi`:
```lua
local zapi = require("maker.main.zapi")
zapi.writeZip("assetDir", "gameasset.zip")
```

**Comment by gphg** [comment]
Ah. I forgot to include the special feature of this module: include and exclude based on string pattern.

**Comment by 2dengine** [comment]
Hello again and thank you for the comments.

All subfolders are included by default when make a new build.
Please note that you can use the following to exclude specific subfolders:
```
build:ignoreMatch("^/%.gitignore")
build:ignoreMatch("^/subfolder")
```

It would be good to be able to make builds from ANY local path however love.filesystem is restricted to the project's directory and the "appdata" folder.
I will consider your suggestion although I do hope to find a more general purpose solution to this problem (without using 3rd party binaries).

**Comment by gphg** [comment]
Understandable.

**Comment by 2dengine** [comment]
Hello Sir, I have an update to the project that allows you to build LOVE files from any path on your hard drive:
```
love.maker = require("maker.main")
love.maker.setExtensions("txt", "png", "json", "xml")
local assetBuild = love.maker.newBuild(path) -- leave blank to build the current source folder
assetBuild:save("gameasset.zip")
```
I have not tested this on Linux, but it appears to work fine on Windows.
Building LOVE files from anywhere requires an intermediate step where the source folder is copied to the AppData directory.
This turns out to be very inefficient, brittle and relies on the operating system.
Overall, it may be better to just have a custom build script inside each of your project folders instead of one centralized script that can build from anywhere.

PS. Also fixed a bug with the temporary filenames.

**Comment by gphg** [comment]
Wow. I didn't expect that. Thanks!

**Comment by 2dengine** [comment]
You are welcome, Sir

**Comment by 2dengine** [comment]
Just pushed an update adding the URFS module.
URFS allows us to build .love files from any location in a very efficient way (no intermediate files).
